# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [2]:
# import NumPy into Python
import numpy as np


# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0, 5001 , (1000, 20))
print(X)
print("The shape of X is:", X.shape)

# print the shape of X


[[2825 4875 4501 ... 4325  562 4156]
 [3691  971 3482 ... 4991 2708 1411]
 [2760 1705  971 ... 2557 3034 3270]
 ...
 [ 689 4683 4690 ... 3073  603  468]
 [2382 2625  732 ...  166  455 2827]
 [1724 1427 1427 ... 2558 1997 1206]]
The shape of X is: (1000, 20)


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [15]:
# Average of the values in each column of X
ave_cols = X.mean(axis = 0)
print("The mean of each column of X is:", ave_cols)

# Standard Deviation of the values in each column of X
std_cols = X.std(axis = 0)
print("The standard deviation of each column of X is:", std_cols)

The mean of each column of X is: [2442.592 2446.127 2471.075 2537.427 2466.539 2441.707 2496.04  2561.495
 2477.858 2473.118 2508.538 2424.335 2457.845 2498.588 2386.544 2456.052
 2353.398 2535.906 2445.247 2483.88 ]
The standard deviation of each column of X is: [1432.16530454 1443.55058272 1442.38326785 1428.77585809 1400.22909143
 1411.93206393 1425.10345393 1452.41053631 1449.54539834 1499.1885959
 1461.78529222 1469.33493145 1448.06339329 1489.10519516 1465.92848259
 1488.03871633 1451.33230433 1455.23957449 1491.00865322 1468.33016505]


If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [9]:
# Print the shape of ave_cols
print(ave_cols.shape)

print(std_cols.shape)
# Print the shape of std_cols


(20,)
(20,)


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [20]:
# Mean normalize X
X_norm = (X - ave_cols)/ std_cols
print(X_norm)

[[ 0.26701387  1.68256868  1.40734092 ...  1.22941544 -1.26306913
   1.1387902 ]
 [ 0.87169267 -1.02187413  0.70087128 ...  1.68707204  0.176225
  -0.73068035]
 [ 0.22162805 -0.51340563 -1.03999751 ...  0.01449521  0.39486894
   0.53538368]
 ...
 [-1.22443408  1.5495633   1.53837406 ...  0.369076   -1.23557096
  -1.37290648]
 [-0.04230797  0.12391183 -1.20569549 ... -1.62853323 -1.33483263
   0.23368041]
 [-0.50175214 -0.70598635 -0.72385407 ...  0.01518238 -0.3006334
  -0.87029473]]


If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [25]:
# Print the average of all the values of X_norm
print(np.mean(X_norm))
print(np.mean(X))
print(X_norm.mean())
print(X_norm.shape)

# Print the average of the minimum value in each column of X_norm


# Print the average of the maximum value in each column of X_norm


-5.684341886080802e-18
2468.21555
-5.684341886080802e-18
(1000, 20)


You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [26]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)


array([0, 2, 1, 3, 4])

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [39]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
print(X_norm)
row_indices = np.random.permutation(X_norm.shape[0])
print

selected_indices = X_norm[row_indices]


[[ 0.26701387  1.68256868  1.40734092 ...  1.22941544 -1.26306913
   1.1387902 ]
 [ 0.87169267 -1.02187413  0.70087128 ...  1.68707204  0.176225
  -0.73068035]
 [ 0.22162805 -0.51340563 -1.03999751 ...  0.01449521  0.39486894
   0.53538368]
 ...
 [-1.22443408  1.5495633   1.53837406 ...  0.369076   -1.23557096
  -1.37290648]
 [-0.04230797  0.12391183 -1.20569549 ... -1.62853323 -1.33483263
   0.23368041]
 [-0.50175214 -0.70598635 -0.72385407 ...  0.01518238 -0.3006334
  -0.87029473]]


Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [48]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.
training_set = int(0.6 * X_norm.shape[0])
crossVal_set = int(0.2 * X_norm.shape[0])
test_set = int(0.2 * X_norm.shape[0])


# Create a Training Set
X_train = X_norm[np.random.choice(row_indices, training_set, replace = False)]
print(X_train)

# Create a Cross Validation Set
X_crossVal = X_norm[np.random.choice(row_indices, crossVal_set, replace = False)]

# Create a Test Set
X_test = X_norm[np.random.choice(row_indices, test_set, replace = False)]

[[-1.62452755 -0.03957395  0.05055868 ... -0.67130252  0.26475567
   0.4121144 ]
 [ 1.0539342  -0.46837777 -1.40675162 ...  0.10451475 -1.21679173
  -1.36813916]
 [-1.70342906  1.45950757  0.77713395 ... -1.47735537 -0.54073932
   1.46024379]
 ...
 [ 0.73693169  0.9364916   0.7175104  ... -0.53730397 -0.93174979
   0.98964118]
 [ 0.61404085 -0.60069042 -1.48440089 ... -0.58609319  0.6631437
  -1.38788949]
 [ 1.35557536 -1.4686891   1.41080741 ...  1.56200672 -1.20606074
   1.4098464 ]]


If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [51]:
# Print the shape of X_train
print(X_train.shape)
# Print the shape of X_crossVal
print(X_crossVal.shape)
# Print the shape of X_test
print(X_test.shape)
Control-C


(600, 20)
(200, 20)
(200, 20)


NameError: name 'Control' is not defined

In [50]:
Control-C


NameError: name 'Control' is not defined